### ISSUE TITLE
Improve CI performance

### ISSUE THREAD

**Issue by lostpg** [sec-bit/ckb-zkp#46]
As the CI flow may take up too much time with the default test profile, consider adding some compilation flags to improve the CI performance.

A compilation flag I used and resulted to a significant improvement used to be [here](https://github.com/sec-bit/ckb-zkp/blob/6878c9bb4e6ba49496ffdb9f0bc91e7bdfbc6d61/Cargo.toml#L47-L48):

```toml
[profile.test]
opt-level = 3
```

It could be put into [./zkp-toolkit/Cargo.toml](https://github.com/sec-bit/ckb-zkp/blob/master/zkp-toolkit/Cargo.toml) now.

**Comment by p0n1** [comment]
got it

**Comment by sunhuachuang** [comment]
use config has side effects when debug in local, maybe use `cargo test --release` in ci is better.
